### PR TITLE
James/header

### PR DESCRIPTION
**Pull request by RobotOptimist**
header as a copy of what is in the current website, seeded data as well

### CODE REVIEW

**Comment by mdchafin** [comment]
I don't see any wireframes for the UI yet it's being coded?

**Comment by RobotOptimist** [comment]
> 

The style and some of the components will remain the same as the old site. The goal of the project is to create a national platform rather than a single location. Some functionality will change based on learning from the previous site. @GregFinzer  can probably provide a more in depth answer on what will be changing.

The header, footer and main page will be a lift and shift from the old site, more or less.

**Comment by mdchafin** [comment]
Hi James,

Greg already wrote to me and let me know what the scope would be; now, with access to the board, things are becoming more apparent.

I noticed that you wrote you just got a Syncfusion Community license. Is that because we will be working with Syncfusion? I have almost two years of experience utilizing it and love it!

This brings me to the header and footer. Are the menus being developed in SFMenu?

I look forward to working with you.

Mike

**Comment by RobotOptimist** [comment]
@mdchafin Absolutely! Glad to have you aboard! I'm a syncfusion newbie, but I've got a fair amount of experience in CMS solutions and software dev in general. These days I'm mostly writing AWS lambdas and stuff in C#. It's fun to get back into some more front end stuff.

**Comment by mdchafin** [comment]
@RobotOptimist Which CMS? I'm a Sitecore certified dev.  I hear ya on getting back to good old app design and coding.

**Pull request merged**
